# Copyright 2020-present, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Davide Abati, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
        'seq-cifar100': {
            'sgd': {-1: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0}},
            'er': {
                500: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0},
                2000: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0}
            },
            'gdumb': {
                500: {'lr': 0.1, 'maxlr': 0.05, 'minlr': 5e-4, 'cutmix_alpha': 1, 'fitting_epochs': 250, 'optim_mom': 0.9, 'optim_wd': 1e-6},
                2000: {'lr': 0.1, 'maxlr': 0.05, 'minlr': 5e-4, 'cutmix_alpha': 1, 'fitting_epochs': 250, 'optim_mom': 0, 'optim_wd': 1e-6},
            },
            'lucir': {
                500: {'lr': 0.03, 'lr_finetune': 0.01, 'optim_mom': 0.9, 'optim_wd': 0, 'lamda_base': 5, 'k_mr': 2, 'fitting_epochs': 20, 'mr_margin': 0.5, 'lamda_mr': 1.},
                2000: {'lr': 0.03, 'lr_finetune': 0.01, 'optim_mom': 0.9, 'optim_wd': 0, 'lamda_base': 5, 'k_mr': 2, 'fitting_epochs': 20, 'mr_margin': 0.5, 'lamda_mr': 1.},
            },

            'icarl': {
                500: {'lr': 0.3, 'optim_mom': 0, 'optim_wd': 1e-05},
                2000: {'lr': 0.3, 'optim_mom': 0, 'optim_wd': 1e-05}
            },
            'bic': {
                500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0},
                2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0},
            },
            'lwf': {
                -1: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 5e-4},
            },

            'er_ace': {
                500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0},
                2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0}
            },
            'rpc': {
                500: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0},
                2000: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0}
            },
            'der': {
                500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.3},
                2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.3}
            },
            'derpp': {
                500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5},
                2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5}
            },
            'xder': {
                500: {'m': 0.7, 'alpha': 0.3, 'beta': 0.8, 'gamma': 0.85, 'optim_wd': 0, 'lambd': 0.05, 'eta': 0.001, 'lr': 0.03, 'simclr_temp': 5, 'optim_mom': 0, 'simclr_batch_size': 64,
                      'simclr_num_aug': 2},
                2000: {'m': 0.2, 'alpha': 0.6, 'beta': 0.9, 'gamma': 0.85, 'optim_wd': 0, 'lambd': 0.05, 'eta': 0.01, 'lr': 0.03, 'simclr_temp': 5, 'optim_mom': 0, 'simclr_batch_size': 64,
                       'simclr_num_aug': 2}
            },
            'esmer': {
                100: {
                    'reg_weight': 0.15,
                    'ema_model_alpha': 0.999,
                    'ema_model_update_freq': 0.07,
                    'loss_margin': 1.2,
                    'loss_alpha': 0.99,
                    'lr': 0.03,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 2,
                    'task_warmup': 1,
                    'std_margin': 1,

                },
                200: {
                    'reg_weight': 0.15,
                    'ema_model_alpha': 0.999,
                    'ema_model_update_freq': 0.07,
                    'loss_margin': 1.0,
                    'loss_alpha': 0.99,
                    'lr': 0.03,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 50,
                    'task_warmup': 1,
                    'std_margin': 1,
                },
            },
        },
    'seq-tinyimg': {'sgd': {-1: {'lr': 0.03,
                                 'batch_size': 32,
                                 'n_epochs': 100}},
                    'ewc_on': {-1: {'lr': 0.03,
                                    'e_lambda': 25,
                                    'gamma': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'si': {-1: {'lr': 0.03,
                                'c': 0.5,
                                'xi': 1.0,
                                'batch_size': 32,
                                'n_epochs': 100}},
                    'lwf': {-1: {'lr': 0.01,
                                 'alpha': 1.0,
                                 'softmax_temp': 2.0,
                                 'batch_size': 32,
                                 'n_epochs': 100,
                                 'wd_reg': 0.0005}},
                    'pnn': {-1: {'lr': 0.03, 'batch_size': 32,
                                 'n_epochs': 100}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 100}},
                    'agem': {200: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             500: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             5120: {'lr': 0.01,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'agem_r': {200: {'lr': 0.01,
                                     'minibatch_size': 32,
                                     'batch_size': 32,
                                     'n_epochs': 100},
                               500: {'lr': 0.01,
                                     'minibatch_size': 32,
                                     'batch_size': 32,
                                     'n_epochs': 100},
                               5120: {'lr': 0.01,
                                      'minibatch_size': 32,
                                      'batch_size': 32,
                                      'n_epochs': 100}},
                    'icarl': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'softmax_temp': 2.0,
                                    'wd_reg': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'softmax_temp': 2.0,
                                    'wd_reg': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'softmax_temp': 2.0,
                                     'wd_reg': 0.00001,
                                     'batch_size': 32,
                                     'n_epochs': 100}},
                    'fdr': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 100}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'softmax_temp': 2.0,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.1,
                                   'batch_size': 32,
                                   'n_epochs': 100}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 100}},
                    'clser': {
                        200: {
                            'reg_weight': 0.1,
                            'stable_model_update_freq': 0.04,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.08,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs': 50,
                        },
                        500: {
                            'reg_weight': 0.1,
                            'stable_model_update_freq': 0.05,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.08,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs': 50,
                        },
                        5120: {
                            'reg_weight': 0.1,
                            'stable_model_update_freq': 0.07,
                            'stable_model_alpha': 0.999,
                            'plastic_model_update_freq': 0.08,
                            'plastic_model_alpha': 0.999,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs': 50,
                        }
                    },

    },
    'mnist-360': {
        'sgd': {-1: {'lr': 0.1, 'batch_size': 4}},
        'er': {200: {'lr': 0.2,
                     'batch_size': 1,
                     'minibatch_size': 16},
               500: {'lr': 0.2, 'batch_size': 1,
                     'minibatch_size': 16},
               1000: {'lr': 0.2,
                      'batch_size': 4,
                      'minibatch_size': 16}},
        'mer': {200: {'lr': 0.2,
                      'minibatch_size': 128,
                      'beta': 1,
                      'gamma': 1,
                      'batch_num': 3},
                500: {'lr': 0.1,
                      'minibatch_size': 128,
                      'beta': 1,
                      'gamma': 1,
                      'batch_num': 3},
                1000: {'lr': 0.2,
                       'minibatch_size': 128,
                       'beta': 1,
                       'gamma': 1,
                       'batch_num': 3}},
        'agem_r': {200: {'lr': 0.1,
                         'batch_size': 16,
                         'minibatch_size': 128},
                   500: {'lr': 0.1,
                         'batch_size': 16,
                         'minibatch_size': 128},
                   1000: {'lr': 0.1,
                          'batch_size': 4,
                          'minibatch_size': 128}},
        'der': {200: {'lr': 0.1,
                      'batch_size': 16,
                      'minibatch_size': 64,
                      'alpha': 0.5},
                500: {'lr': 0.2,
                      'batch_size': 16,
                      'minibatch_size': 16,
                      'alpha': 0.5},
                1000: {'lr': 0.1,
                       'batch_size': 8,
                       'minibatch_size': 16,
                       'alpha': 0.5}},
        'derpp': {200: {'lr': 0.2,
                        'batch_size': 16,
                        'minibatch_size': 16,
                        'alpha': 0.5,
                        'beta': 1.0},
                  500: {'lr': 0.2,
                        'batch_size': 16,
                        'minibatch_size': 16,
                        'alpha': 0.5,
                        'beta': 1.0},
                  1000: {'lr': 0.2,
                         'batch_size': 16,
                         'minibatch_size': 128,
                         'alpha': 0.2,
                         'beta': 1.0}},
        'clser': {
            200: {
                'reg_weight': 0.75,
                'stable_model_update_freq': 1,
                'stable_model_alpha': 0.999,
                'plastic_model_update_freq': 1,
                'plastic_model_alpha': 0.99,
                'lr': 0.2,
                'minibatch_size': 16,
                'batch_size': 16,
                'n_epochs': 1,
            },
            500: {
                'reg_weight': 1.25,
                'stable_model_update_freq': 0.9,
                'stable_model_alpha': 0.99,
                'plastic_model_update_freq': 1,
                'plastic_model_alpha': 0.99,
                'lr': 0.2,
                'minibatch_size': 32,
                'batch_size': 16,
                'n_epochs': 1,
            },
            1000: {
                'reg_weight': 0.75,
                'stable_model_update_freq': 0.9,
                'stable_model_alpha': 0.99,
                'plastic_model_update_freq': 1,
                'plastic_model_alpha': 0.99,
                'lr': 0.2,
                'minibatch_size': 128,
                'batch_size': 16,
                'n_epochs': 1,
            }
        },
    },
    'gcil-cifar100': {
        'sgd': {
            'unif': {
            -1: {
                'lr': 0.1,
                'batch_size': 32,
                'n_epochs': 100
                }
            },
            'longtail': {
                -1: {
                    'lr': 0.1,
                    'batch_size': 32,
                    'n_epochs': 100
                }
            },
        },
        'er': {
            'unif': {
                200: {
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                500: {
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
            'longtail': {
                200: {
                    'alpha': 0.2,
                    'beta': 0.6,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                500: {
                    'alpha': 0.2,
                    'beta': 0.8,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'alpha': 0.3,
                    'beta': 0.9,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
        },
        'derpp': {
            'unif': {
                200: {
                    'alpha': 0.2,
                    'beta': 0.5,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                500: {
                    'alpha': 0.2,
                    'beta': 0.6,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'alpha': 0.3,
                    'beta': 0.6,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
            'longtail': {
                200: {
                    'alpha': 0.2,
                    'beta': 0.6,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                500: {
                    'alpha': 0.2,
                    'beta': 0.8,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'alpha': 0.3,
                    'beta': 0.9,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
        },
        'clser': {
            'unif': {
                200: {
                    'reg_weight': 0.15,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.7,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 200,
                },
                500: {
                    'reg_weight': 0.15,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.9,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'reg_weight': 0.15,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.8,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
            'longtail': {
                200: {
                    'reg_weight': 0.1,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.7,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                500: {
                    'reg_weight': 0.1,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.7,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
                1000: {
                    'reg_weight': 0.1,
                    'stable_model_update_freq': 0.6,
                    'stable_model_alpha': 0.999,
                    'plastic_model_update_freq': 0.8,
                    'plastic_model_alpha': 0.999,
                    'lr': 0.1,
                    'minibatch_size': 32,
                    'batch_size': 32,
                    'n_epochs': 100,
                },
            },
        },
        'esmer': {
            'unif': {
                100: {
                'reg_weight': 0.2,
                'ema_model_alpha': 0.999,
                'ema_model_update_freq': 0.2,
                'loss_margin': 2.5,
                'loss_alpha': 0.99,
                'lr': 0.05,
                'minibatch_size': 32,
                'batch_size': 32,
                'n_epochs': 50,
                'task_warmup': 1,
                'std_margin': 1,
            },
            200: {
                'reg_weight': 0.2,
                'ema_model_alpha': 0.999,
                'ema_model_update_freq': 0.2,
                'loss_margin': 2.5,
                'loss_alpha': 0.99,
                'lr': 0.05,
                'minibatch_size': 32,
                'batch_size': 32,
                'n_epochs': 50,
                'task_warmup': 1,
                'std_margin': 1,
            },
        },
        'longtail': {
            100: {
                'reg_weight': 0.2,
                'ema_model_alpha': 0.999,
                'ema_model_update_freq': 0.2,
                'loss_margin': 3.0,
                'loss_alpha': 0.99,
                'lr': 0.03,
                'minibatch_size': 32,
                'batch_size': 32,
                'n_epochs': 50,
                'task_warmup': 1,
                'std_margin': 1,
            },
            200: {
                'reg_weight': 0.2,
                'ema_model_alpha': 0.999,
                'ema_model_update_freq': 0.2,
                'loss_margin': 2.5,
                'loss_alpha': 0.99,
                'lr': 0.03,
                'minibatch_size': 32,
                'batch_size': 32,
                'n_epochs': 50,
                'task_warmup': 1,
                'std_margin': 1,
            },
        },
        }
    },
}

